spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventstore
  kafka:
    topic: order-events
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8082
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8082
        specific.avro.reader: true
      auto-offset-reset: earliest

server:
  port: 8080